language: ruby
rvm:
  - 1.9.3
cache: bundler
script:
  - RAILS_ENV=test bundle exec rake
before_script:
  - RAILS_ENV=test bundle exec rake db:schema:load
  - RAILS_ENV=test bundle exec rake db:test:prepare
